version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-gue
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: djava_luxurydb
    networks:
      - djava-net
    ports:
      - "3306:3306"

  app:
    image: rombenc/djava-luxury-app
    container_name: djava-luxury-app
    depends_on:
      - mysql
    networks:
      - djava-net
    ports:
      - "8080:8080"

networks:
  djava-net:
    driver: bridge
